trigger:
  branches:
    include:
      - main

variables:
  - group: mlops-vk-vg

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RegisterModel
  displayName: 'Register Model Job'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python Version to 3.8'
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r package_requirement/requirements.txt
    displayName: 'Install Dependencies'

  - task: AzureCLI@2
    displayName: 'Add Azure ML Extension'
    inputs:
      azureSubscription: 'azure-service-connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Remove conflicting extension if it exists
        if az extension list --query "[?name=='azure-cli-ml']" | grep -q 'azure-cli-ml'; then
          az extension remove -n azure-cli-ml
        fi

        # Ensure the ml extension is installed
        if ! az extension list --query "[?name=='ml']" | grep -q 'ml'; then
          az extension add -n ml --allow-preview true
        fi

  - script: |
      echo "Current directory: $(pwd)"
      echo "Listing all files in the current directory:"
      ls -la
    displayName: 'Debug Current Directory'

  - script: |
      mkdir -p $(Build.SourcesDirectory)/deployment/outputs/models
      echo "Created outputs/models directory"
    displayName: 'Create Outputs Directory'

  - script: |
      # Assuming the model file is generated by a previous step
      # Here we simulate the generation of the model file
      touch $(Build.SourcesDirectory)/deployment/outputs/models/insurance_model.pkl
      echo "Simulated model file creation"
    displayName: 'Simulate Model File Creation'

  - script: |
      ls -la $(Build.SourcesDirectory)/deployment/outputs/models/
    displayName: 'List Model Directory Contents'

  - task: AzureCLI@2
    displayName: 'Upload Model to Azure Blob Storage'
    inputs:
      azureSubscription: 'azure-service-connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload \
          --account-name $(storageAccountName) \
          --container-name $(containerName) \
          --name insurance_model.pkl \
          --file $(Build.SourcesDirectory)/deployment/outputs/models/insurance_model.pkl
    env:
      AZURE_STORAGE_KEY: $(storageAccountKey)

  - script: |
      echo "Current directory: $(pwd)"
      echo "Listing all files in the current directory:"
      ls -la
    displayName: 'Debug Current Directory 2'
